import { type ResolvingMetadata, type Metadata } from "next";
import { redirect } from "next/navigation";
import { Footer } from "~/components/layout/Footer";
import { Navbar } from "~/components/layout/Navbar";
import Room from "~/components/Room";
import { env } from "~/env";
import { getRoom } from "~/lib/cache/redis";

type Props = {
  params: { roomId: string };
  searchParams: Record<string, string | string[] | undefined>;
};

export async function generateMetadata(
  { params }: Props,
  parent: ResolvingMetadata,
): Promise<Metadata> {
  // read route params
  const id = params.roomId;

  // fetch data
  const room = await getRoom(id);

  // optionally access and extend (rather than replace) parent metadata
  const previousImages = (await parent).openGraph?.images ?? [];

  const metadata: Metadata = {
    title:
      (room !== null
        ? ("[" + id + "] Playing " + room.targetState.playing.title ??
          room.targetState.playing.src[0]?.src)
        : "Null room...") +
      " | " +
      env.SITE_NAME,
    description: "Watch videos or play music in sync with your friends",
    openGraph: {
      images: ["/apple-touch-icon.png", ...previousImages],
    },
    icons: [
      { rel: "icon", url: "/apple-touch-icon.png" },
      { rel: "icon", url: "/favicon.ico" },
    ],
    robots: "noindex, noarchive, nofollow",
  };
  return metadata;
}

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RoomPage({ params }: { params: { roomId: string } }) {
  if (params.roomId.length < 4) {
    redirect("/");
  }

  return (
    <>
      <Navbar roomId={params.roomId} />
      <Room id={params.roomId} />
      <Footer />
    </>
  );
}
